/**
 * Indexing & Sitemap Engine — type definitions
 *
 * IMPORTANT — Google Indexing API scope:
 *   The Google Indexing API is intended ONLY for pages containing
 *   JobPosting or BroadcastEvent (livestream) structured data.
 *   It must NOT be used to request indexing of standard service or
 *   location pages such as those generated by this system.
 *   For normal pages, submit the sitemap.xml URL via Google Search Console.
 */

// ─── Input ────────────────────────────────────────────────────────────────────

export type PageReadiness = "ready" | "review" | "blocked";
export type PageType      = "hub" | "cluster" | "supporting";

export interface IndexingPageInput {
  url:        string;
  pageType:   PageType;
  readiness:  PageReadiness;
  outputPath: string;
  lastmod?:   string;
}

export interface IndexingEngineInput {
  projectSlug: string;
  baseUrl:     string;
  pages:       IndexingPageInput[];
}

// ─── Sitemap ──────────────────────────────────────────────────────────────────

export interface SitemapEntry {
  loc:        string;
  lastmod:    string;
  changefreq: "weekly";
  priority:   0.9 | 0.8 | 0.6;
}

// ─── Excluded page record ─────────────────────────────────────────────────────

export interface ExcludedPage {
  url:    string;
  reason: string;
}

// ─── Report ───────────────────────────────────────────────────────────────────

export interface IndexingReport {
  sitemapUrl:     string;
  robotsUrl:      string;
  totalInputUrls: number;
  includedUrls:   number;
  excludedUrls:   ExcludedPage[];
  hubCount:       number;
  clusterCount:   number;
  supportingCount: number;
  generatedAt:    string;
}

// ─── Engine output ────────────────────────────────────────────────────────────

export interface IndexingEngineOutput {
  sitemapXml:  string;
  robotsTxt:   string;
  report:      IndexingReport;
}

// ─── Priority map ─────────────────────────────────────────────────────────────

export const PAGE_PRIORITY: Record<PageType, 0.9 | 0.8 | 0.6> = {
  hub:        0.9,
  cluster:    0.8,
  supporting: 0.6,
};
