import { getDefaultMediaTextLayoutThresholds } from "./pharmacyMediaTextLayoutResolver.ts";
import { getPharmaConnectBrandDnaComponentDefaults } from "./pharmacyBrandDnaComponentDefaults.ts";
import { defaultImageSlotTreatments, resolveHeaderCtaButtonStyles, resolveHeroContactTreatment } from "./pharmacyComponentDnaStyleResolver.ts";

export function getPharmaConnectComponentDnaDefaults(): ComponentDna {
  const variants = getPharmaConnectBrandDnaComponentDefaults();
  const headerCtas = resolveHeaderCtaButtonStyles(
    {
      semanticColours: { primaryAction: "#66a960", primaryActionText: "#ffffff" },
      colours: { button: "#66a960", buttonText: "#ffffff" },
      surfaces: { buttonRadius: "14px", buttonWeight: "700" },
    } as import("./pharmacyBrandDnaTypes.ts").BrandDnaV1,
    "14px",
    "8px 14px",
  );
  const slotTreatments = defaultImageSlotTreatments("16 / 10", "4 / 3", "21 / 9");
  return {
    variants,
    header: {
      logoPosition: "left",
      logoMaxHeight: "48px",
      navGap: "24px",
      navAlign: "end",
      navFontSize: "14px",
      ctaLayout: "group",
      ctaGap: "10px",
      sticky: true,
      topBar: false,
      phoneTreatment: "hidden",
      emailTreatment: "plain",
      socialTreatment: "hidden",
      desktopBreakpoint: "980px",
      mobileBreakpoint: "640px",
      variant: variants.headerVariant,
      topBarVariant: variants.topBarVariant,
      navigationVariant: variants.navigationVariant,
      mobileHeaderVariant: variants.mobileHeaderVariant,
    },
    footer: {
      columnWidths: "2.2fr 1fr 1.15fr 1.5fr",
      columnOrder: ["about", "quickLinks", "openingHours", "contact"],
      columnGap: "40px",
      headingSpacing: "16px",
      paragraphSpacing: "10px",
      sectionPaddingTop: "56px",
      sectionPaddingBottom: "0",
      bottomBarPadding: "18px",
      hoursTableLayout: "table",
      contactIconSize: "36px",
      contactIconStyle: "circular-outlined",
      socialIconSize: "38px",
      socialIconStyle: "circular-outlined",
      badgePlacement: "brand-column",
      badgeMaxHeight: "56px",
      badgeAlignment: "start",
      badgeSpacing: "10px",
      badgeImageFallbackText: true,
      legalBarLayout: "split",
      patternTreatment: "generic",
      backToTop: true,
      stackOrder: ["about", "quickLinks", "openingHours", "contact"],
      variant: variants.footerVariant,
    },
    hero: {
      layout: variants.heroVariant,
      textColumnRatio: "1fr",
      imageColumnRatio: "1fr",
      verticalAlign: "center",
      gap: "48px",
      paddingY: "96px",
      maxTextWidth: "720px",
      variant: variants.heroVariant,
    },
    splitSection: {
      textRatio: "1fr",
      imageRatio: "1fr",
      desktopLayout: "text-left",
      mobileStack: "text-first",
      verticalAlign: "center",
      gap: "32px",
      paddingY: "84px",
      maxWidth: "1180px",
      sectionSpacing: "84px",
      variant: variants.mediaTextVariant,
      flowVariant: variants.sectionFlowVariant,
      compositionMode: "media-float-flow",
      contentContinuation: true,
      layoutThresholds: getDefaultMediaTextLayoutThresholds(),
    },
    image: {
      heroAspectRatio: "16 / 10",
      inlineAspectRatio: "4 / 3",
      sectionAspectRatio: "21 / 9",
      maxHeight: "520px",
      borderRadius: "10px",
      shadow: "var(--brand-card-shadow, var(--shadow))",
      splitRatio: "1fr 1fr",
      alignment: "center",
      objectFit: "cover",
      responsiveCrop: true,
      variant: variants.imageTreatmentVariant,
      slotTreatments,
    },
    map: {
      minHeight: "440px",
      borderRadius: "10px",
      containerPadding: "0",
      headingStyle: "section-head",
      gap: "32px",
      layout: variants.mapContactVariant,
      iframeBorder: "0",
      stackBelow: "980px",
      mapColumnRatio: "1.65fr",
      detailsColumnRatio: "0.95fr",
      stackOrder: "details-first",
    },
    card: {
      radius: "var(--brand-radius-card, 26px)",
      shadow: "var(--brand-card-shadow, var(--shadow))",
      padding: "24px",
      headingSpacing: "12px",
      iconPlacement: "top",
      border: "1px solid var(--line)",
      hoverTreatment: "lift",
      columns: 3,
      gap: "24px",
      variant: variants.serviceCardVariant,
    },
    cta: {
      buttonFamily: "filled-only",
      spacing: "8px 14px",
      alignment: "center",
      dualCta: true,
      iconSpacing: "8px",
      buttonRadius: "14px",
      bandPadding: "84px",
      variant: variants.ctaVariant,
      headerPrimary: headerCtas.headerPrimary,
      headerSecondary: headerCtas.headerSecondary,
    },
    contact: resolveHeroContactTreatment({
      semanticColours: { primaryAction: "#66a960", primaryActionText: "#ffffff" },
      colours: { button: "#66a960", buttonText: "#ffffff" },
      surfaces: { buttonRadius: "10px" },
    } as import("./pharmacyBrandDnaTypes.ts").BrandDnaV1),
    faq: {
      style: variants.faqVariant,
      itemSpacing: "16px",
      icon: "none",
      headingSize: "1.125rem",
      bodySpacing: "12px",
      padding: "20px",
    },
    process: {
      layout: variants.processVariant,
      stepSpacing: "24px",
      numberStyle: "badge",
      connector: false,
      cardPadding: "24px",
      columns: 4,
    },
    trust: {
      layout: variants.trustPanelVariant,
      cardColumns: 4,
      badgeLayout: "inline",
      evidenceLayout: "grid",
      iconTreatment: "circular-outlined",
      spacing: "24px",
      gap: "20px",
    },
    table: {
      rowBorder: "1px solid color-mix(in srgb, var(--brand-footer-text, #fff) 14%, transparent)",
      cellPadding: "10px 0",
      headerWeight: "600",
      columnAlign: "split",
      stripe: false,
    },
  };
}
