import express, { Router, type IRouter } from "express";
import healthRouter from "./health";
import previewRouter from "./preview";
import setupRouter from "./setup";
import pharmacySetupPageRouter from "./pharmacySetupPage";
import pharmacyPreviewV2Router from "./pharmacyPreviewV2";
import pharmacyAreaPreviewV1Router from "./pharmacyAreaPreviewV1";
import pharmacyMasterPreviewRouter from "./pharmacyMasterPreview";
import pharmacyContentEcosystemPreviewRouter from "./pharmacyContentEcosystemPreview";
import pharmacyVisualExperiencePreviewRouter from "./pharmacyVisualExperiencePreview";
import pharmacyResearchPreviewRouter from "./pharmacyResearchPreview";
import pharmacyIntelligencePageRouter from "./pharmacyIntelligencePage";
import pharmacyCompetitorDashboardPageRouter from "./pharmacyCompetitorDashboardPage";
import pharmacyExecutiveDashboardPageRouter from "./pharmacyExecutiveDashboardPage";
import pharmacyProfileDashboardPageRouter from "./pharmacyProfileDashboardPage";
import pharmacyProfileWizardPageRouter from "./pharmacyProfileWizardPage";
import pharmacyProfileQualityPageRouter from "./pharmacyProfileQualityPage";
import pharmacyPlatformDashboardPageRouter from "./pharmacyPlatformDashboardPage";
import pharmacyLongTermGrowthPageRouter from "./pharmacyLongTermGrowthPage";
import pharmacyGrowthDashboardPageRouter from "./pharmacyGrowthDashboardPage";
import pharmacyGrowthActionsPageRouter from "./pharmacyGrowthActionsPage";
import pharmacyCampaignsPageRouter from "./pharmacyCampaignsPage";
import pharmacyCampaignLaunchQueuePageRouter from "./pharmacyCampaignLaunchQueuePage";
import pharmacyLaunchDemoPageRouter from "./pharmacyLaunchDemoPage";
import rankingRouter from "./ranking";
import dashboardRouter from "./dashboard";
import imagePromptsPageRouter from "./imagePromptsPage";
import imageUploadPageRouter from "./imageUploadPage";
import designsRouter from "./designs";
import projectsRouter from "./api/projects";
import areaEngineRouter from "./api/areaEngine";
import selectedAreasRouter from "./api/selectedAreas";
import rolloutRouter from "./api/rollout";
import validateRouter from "./api/validate";
import sessionRouter from "./api/session";
import searchConsoleRouter from "./api/searchConsole";
import indexTrackingRouter from "./api/indexTracking";
import indexDashboardRouter from "./api/indexDashboard";
import rankTrackingRouter from "./api/rankTracking";
import seoOpportunitiesRouter from "./api/seoOpportunities";
import seoHealthScoreRouter from "./api/seoHealthScore";
import dashboardSeoIntelligenceRouter from "./api/dashboardSeoIntelligence";
import gscSummaryRouter from "./api/gscSummary";
import gscIndexRouter from "./api/gscIndex";
import keywordTrackingRouter from "./api/keywordTracking";
import imagesRouter from "./api/images";
import usageRouter from "./api/usage";
import campaignsRouter from "./api/campaigns";
import gscAuthRouter from "./api/gscAuth";
import templatesRouter from "./api/templates";
import generateRouter        from "./api/generate";
import suggestKeywordsRouter from "./api/suggestKeywords";
import prePublishQaRouter    from "./api/prePublishQa";
import liveCrawlRouter       from "./api/liveCrawl";
import systemHealthRouter    from "./api/systemHealth";
import systemDiagnosticsRouter from "./api/systemDiagnostics";
import securityScanRouter   from "./api/securityScan";
import linkAuditRouter      from "./api/linkAudit";
import distributionRouter   from "./api/distribution";
import publishGateRouter    from "./api/publishGate";
import imageLibraryRouter  from "./api/imageLibrary";
import imagePromptDashboardRouter from "./api/imagePromptDashboard";
import brandImportRouter      from "./api/brandImport";
import providerProfilesRouter from "./api/providerProfiles";
import usersRouter            from "./api/users";
import socialPostsRouter      from "./api/socialPosts";
import contentRouter          from "./api/content";
import sectionOptimiseRouter  from "./api/sectionOptimise";
import pharmacySetupRouter    from "./api/pharmacySetup";
import pharmacyProfilesRouter from "./api/pharmacyProfiles";
import pharmacyIntelligenceRouter from "./api/pharmacyIntelligence";
import pharmacyCompetitorIntelligenceRouter from "./api/pharmacyCompetitorIntelligence";
import pharmacyExecutiveDashboardRouter from "./api/pharmacyExecutiveDashboard";
import pharmacyGrowthJourneyRouter from "./api/pharmacyGrowthJourney";
import pharmacyLocalIntelligenceRouter from "./api/pharmacyLocalIntelligence";
import pharmacyServiceAreaPagesRouter from "./api/pharmacyServiceAreaPages";
import pharmacyPublishingRouter from "./api/pharmacyPublishing";
import pharmacyIndexingRouter from "./api/pharmacyIndexing";
import pharmacyVisibilityRouter from "./api/pharmacyVisibility";
import pharmacyGrowthActionsRouter from "./api/pharmacyGrowthActions";
import pharmacyCampaignsRouter from "./api/pharmacyCampaigns";
import pharmacyCampaignLaunchQueueRouter from "./api/pharmacyCampaignLaunchQueue";
import pharmacyImageLibraryRouter from "./api/pharmacyImageLibrary";
import pharmacyImageLibraryPageRouter from "./pharmacyImageLibraryPage";
import pharmacyAuthorityReadinessRouter from "./api/pharmacyAuthorityReadiness";
import pharmacyAuthorityReadinessPageRouter from "./pharmacyAuthorityReadinessPage";
import pharmacyAuthorityEnhancementsRouter from "./api/pharmacyAuthorityEnhancements";
import pharmacyAuthorityEnhancementsPageRouter from "./pharmacyAuthorityEnhancementsPage";
import pharmacyEnhancementWorkspaceRouter from "./api/pharmacyEnhancementWorkspace";
import pharmacyEnhancementWorkspacePageRouter from "./pharmacyEnhancementWorkspacePage";
import pharmacyPublishingSettingsPageRouter from "./pharmacyPublishingSettingsPage";
import pharmacyPublishingSettingsRouter from "./api/pharmacyPublishingSettings";
import pharmacyFaqWorkspacePlaceholderPageRouter from "./pharmacyFaqWorkspacePlaceholderPage";
import pharmacyStructuredDataReviewPlaceholderPageRouter from "./pharmacyStructuredDataReviewPlaceholderPage";
import adminRouter            from "./admin";
import pharmacyMasterAdminPageRouter from "./pharmacyMasterAdminPage";
import masterAdminPlatformPageRouter from "./masterAdminPlatformPage";
import pharmacyMasterAdminApiRouter from "./api/pharmacyMasterAdmin";
import masterAdminPlatformApiRouter from "./api/masterAdminPlatform";
import masterAdminIssuesApiRouter from "./api/masterAdminIssues";
import masterAdminIssuePageRouter from "./masterAdminIssuePage";
import growthEnginePageRouter from "./growthEnginePageRouter";
import growthEngineApiRouter from "./api/growthEngine";
import pharmacyContentPackagePageRouter from "./pharmacyContentPackagePage";
import pharmacyContentPackageRouter from "./api/pharmacyContentPackage";
import growthEngineReviewCentrePageRouter from "./growthEngineReviewCentrePageRouter";
import growthEngineCampaignBuilderPageRouter from "./growthEngineCampaignBuilderPageRouter";
import growthEngineCampaignBuilderRouter from "./api/growthEngineCampaignBuilder";
import growthEngineReviewCentreRouter from "./api/growthEngineReviewCentre";
import pharmacyAssetWorkflowRouter from "./api/pharmacyAssetWorkflow";
import pharmacyAssetReviewPageRouter from "./pharmacyAssetReviewPage";


const router: IRouter = Router();

// Root redirect → dashboard
router.get("/", (_req, res) => res.redirect("/api/dashboard"));

// UI routes
router.use(setupRouter);
router.use(pharmacySetupPageRouter);
router.use(pharmacyPreviewV2Router);
router.use(pharmacyAreaPreviewV1Router);
router.use(pharmacyMasterPreviewRouter);
router.use(pharmacyContentEcosystemPreviewRouter);
router.use(pharmacyVisualExperiencePreviewRouter);
router.use(pharmacyResearchPreviewRouter);
router.use(pharmacyIntelligencePageRouter);
router.use(pharmacyCompetitorDashboardPageRouter);
router.use(pharmacyExecutiveDashboardPageRouter);
router.use(growthEnginePageRouter);
router.use(growthEngineReviewCentrePageRouter);
router.use(growthEngineCampaignBuilderPageRouter);
router.use(pharmacyPlatformDashboardPageRouter);
router.use(pharmacyLongTermGrowthPageRouter);
router.use(pharmacyProfileDashboardPageRouter);
router.use(pharmacyProfileWizardPageRouter);
router.use(pharmacyProfileQualityPageRouter);
router.use(pharmacyGrowthDashboardPageRouter);
router.use(pharmacyGrowthActionsPageRouter);
router.use(pharmacyCampaignsPageRouter);
router.use(pharmacyCampaignLaunchQueuePageRouter);
router.use(pharmacyImageLibraryPageRouter);
router.use(pharmacyAuthorityReadinessPageRouter);
router.use(pharmacyAuthorityEnhancementsPageRouter);
router.use(pharmacyEnhancementWorkspacePageRouter);
router.use(pharmacyAssetReviewPageRouter);
router.use(pharmacyContentPackagePageRouter);
router.use(pharmacyPublishingSettingsPageRouter);
router.use(pharmacyFaqWorkspacePlaceholderPageRouter);
router.use(pharmacyStructuredDataReviewPlaceholderPageRouter);
router.use(pharmacyLaunchDemoPageRouter);
router.use(pharmacyMasterAdminPageRouter);
router.use(masterAdminPlatformPageRouter);
router.use(masterAdminIssuePageRouter);
router.use(rankingRouter);
router.use(dashboardRouter);
router.use(imagePromptsPageRouter);
router.use(imageUploadPageRouter);
router.use(designsRouter);
router.use(healthRouter);

// JSON API routes
router.use(projectsRouter);
router.use(areaEngineRouter);
router.use(selectedAreasRouter);
router.use(rolloutRouter);
router.use(validateRouter);
router.use(sessionRouter);
router.use(searchConsoleRouter);
router.use(indexTrackingRouter);
router.use(indexDashboardRouter);
router.use(rankTrackingRouter);
router.use(seoOpportunitiesRouter);
router.use(seoHealthScoreRouter);
router.use(dashboardSeoIntelligenceRouter);
router.use(gscSummaryRouter);
router.use(gscIndexRouter);
router.use(keywordTrackingRouter);
router.use(imagesRouter);
router.use(usageRouter);
router.use(campaignsRouter);
router.use(gscAuthRouter);
router.use(templatesRouter);
router.use(generateRouter);
router.use(suggestKeywordsRouter);
router.use(prePublishQaRouter);
router.use(liveCrawlRouter);
router.use(systemHealthRouter);
router.use(systemDiagnosticsRouter);
router.use(securityScanRouter);
router.use(linkAuditRouter);
router.use(distributionRouter);
router.use(publishGateRouter);
router.use(imageLibraryRouter);
router.use(imagePromptDashboardRouter);
router.use(brandImportRouter);
router.use(providerProfilesRouter);
router.use(usersRouter);
router.use(socialPostsRouter);
router.use(contentRouter);
router.use(sectionOptimiseRouter);
router.use(pharmacySetupRouter);
router.use(pharmacyProfilesRouter);
router.use(pharmacyIntelligenceRouter);
router.use(pharmacyCompetitorIntelligenceRouter);
router.use(pharmacyExecutiveDashboardRouter);
router.use(pharmacyGrowthJourneyRouter);
router.use(pharmacyLocalIntelligenceRouter);
router.use(pharmacyServiceAreaPagesRouter);
router.use(pharmacyPublishingRouter);
router.use(pharmacyIndexingRouter);
router.use(pharmacyVisibilityRouter);
router.use(pharmacyGrowthActionsRouter);
router.use(pharmacyCampaignsRouter);
router.use(pharmacyCampaignLaunchQueueRouter);
router.use(pharmacyImageLibraryRouter);
router.use(growthEngineApiRouter);
router.use(growthEngineCampaignBuilderRouter);
router.use(growthEngineReviewCentreRouter);
router.use(pharmacyAssetWorkflowRouter);
router.use(pharmacyContentPackageRouter);
router.use(pharmacyAuthorityReadinessRouter);
router.use(pharmacyAuthorityEnhancementsRouter);
router.use(pharmacyEnhancementWorkspaceRouter);
router.use(pharmacyPublishingSettingsRouter);
router.use(pharmacyMasterAdminApiRouter);
router.use(masterAdminPlatformApiRouter);
router.use(masterAdminIssuesApiRouter);
router.use(adminRouter);





export default router;
