// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/saas-nav/DarkSidebar.tsx": () => import("../components/mockups/saas-nav/DarkSidebar.tsx"),
  "./components/mockups/saas-nav/DarkSidebarFull.tsx": () => import("../components/mockups/saas-nav/DarkSidebarFull.tsx"),
  "./components/mockups/saas-nav/DarkSidebarWizard.tsx": () => import("../components/mockups/saas-nav/DarkSidebarWizard.tsx"),
  "./components/mockups/saas-nav/LightSidebar.tsx": () => import("../components/mockups/saas-nav/LightSidebar.tsx"),
  "./components/mockups/saas-nav/TopHybrid.tsx": () => import("../components/mockups/saas-nav/TopHybrid.tsx"),
  "./components/mockups/seo-wizard-command/CommandCenter.tsx": () => import("../components/mockups/seo-wizard-command/CommandCenter.tsx"),
  "./components/mockups/seo-wizard-glass/GlassPro.tsx": () => import("../components/mockups/seo-wizard-glass/GlassPro.tsx"),
  "./components/mockups/seo-wizard-stepper/CleanStepper.tsx": () => import("../components/mockups/seo-wizard-stepper/CleanStepper.tsx")
};
